name: NuGet Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: 'write-all'

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing NBGV
      run: dotnet tool install --tool-path . nbgv
    - name: Bumping version
      run: .\nbgv cloud
    - name: Getting version
      run: echo "VERSION=$(nbgv get-version -v SimpleVersion)" >> $GITHUB_ENV
    - name: Output tag
      run: |
        echo $VERSION
