name: NuGet Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: 'write-all'

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing NBGV
      run: dotnet tool install --tool-path ../../nbvg_folder nbgv
    - name: Seting git username
      run: git config --global user.name "GitHub Actions"
    - name: Seting git email
      run: git config --global user.email miraslau.kazak@slalom.com
    - name: Bumping version
      run: nbgv prepare-release --versionIncrement Minor
    - name: Push changes to repo
      run: git push
    - name: Build
      run: dotnet build
    - name: Getting version
      run: echo "VERSION=$(nbgv get-version -v SimpleVersion)" >> $GITHUB_ENV
    - name: Output version
      run: |
        echo $VERSION
